[package]
name = "rustuna_core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
rand = { workspace = true }
rand_distr = "0.4.3"

[dev-dependencies]
statrs = "0.18.0"
