[package]
name = "rustuna_core"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
rand = { workspace = true }
rand_distr = "0.4.3"
statrs = "0.18.0"
lasso = { version = "0.7", features = ["multi-threaded"] }
once_cell = "1.21"
