version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
    rust: "latest"
  jobs:
    pre_build:
      - cd docs && source .venv/bin/activate && cd ../rustuna_pyo3 && maturin develop

mkdocs:
  configuration: docs/mkdocs.yml
  fail_on_warning: false

python:
  install:
    - method: uv
      command: sync
      path: docs
      groups:
        - docs
