[package]
name = "rustuna_pyo3"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "README.md"

[lib]
name = "rustuna"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module", "chrono"] }
chrono = { workspace = true }
rustuna_core = { workspace = true }
rustuna_samplers = { workspace = true }
rustuna_storages = { workspace = true }
rustuna_importance = { workspace = true }
fanova = { workspace = true }
