[build-system]
requires = ["maturin>=1.3,<2.0"]
build-backend = "maturin"

[project]
name = "rustuna"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "rustuna._rustuna"

[tool.ruff.lint]
select = ["E", "I"] # pycodestyle and isort
ignore = ["E501"]

[dependency-groups]
dev = [
    # TODO(c-bata): Change to optuna/optuna@master after merging Optuna PR #6391.
    "optuna @ git+https://github.com/c-bata/optuna.git@follow-up-storage-test-case",
    "ruff",
    "pytest",
    "mypy",
    "freezegun",
]
