//! Quasi-Monte Carlo sampler built on the Sobol' sequence.

use std::collections::HashMap;
use std::sync::{Arc, RwLock};

use rustuna_core::attr::{AttrKey, Attrs};
use rustuna_core::distribution::Distribution;
use rustuna_core::sampler::{Context, RandomSampler, Sampler};
use rustuna_core::storage::Storage;
use rustuna_core::transform::SearchSpaceTransform;
use rustuna_core::trial::TrialStateValues;
use rustuna_core::{Error, ErrorKind, Result};

use super::SobolEngine;

/// A Quasi-Monte Carlo Sampler that generates low-discrepancy sequences.
///
/// This sampler is the Rustuna counterpart of Optuna's `QMCSampler`. It covers the search space
/// with a low-discrepancy sequence instead of independent random draws, so a given number of
/// trials spreads more evenly than random search does. The sequence is generated by
/// [`SobolEngine`], which matches `scipy.stats.qmc.Sobol(d, scramble=False)`. Scrambling is not
/// implemented yet.
///
/// Sobol' points are most uniform when the number of trials is a power of two. Parameters
/// outside the joint search space, including everything in the first trial, fall back to
/// random sampling.
///
/// The position in the sequence is kept in a study system attribute rather than in the sampler,
/// so workers sharing a storage walk one sequence together and a resumed study continues where it
/// left off. Threads within one process are serialized by the storage lock, but two processes can
/// reserve the same index, because reading and writing the counter is not a single storage
/// transaction.
///
/// # Examples
///
/// ```no_run
/// use rustuna_core::storage::InMemoryStorage;
/// use rustuna_core::study::{create_study, Direction};
/// use rustuna_core::Result;
/// use rustuna_sampler::qmc::QmcSampler;
///
/// fn main() -> Result<()> {
///     let storage = InMemoryStorage::new();
///     let study = create_study(
///         "simple-quadratic",
///         storage,
///         QmcSampler::new(),
///         vec![Direction::Minimize],
///     )?;
///
///     study.optimize(
///         |mut trial| {
///             let x = trial.suggest_float("x", -10.0, 10.0)?;
///             Ok(vec![x * x])
///         },
///         64,
///     )?;
///     Ok(())
/// }
/// ```
pub struct QmcSampler {
    independent_sampler: RandomSampler,
    /// Direction numbers depend only on the number of dimensions, so the engine is kept around
    /// and rebuilt only when the joint search space changes size.
    engine: Option<SobolEngine>,
}

impl Default for QmcSampler {
    fn default() -> Self {
        Self::new()
    }
}

impl QmcSampler {
    /// Creates a sampler whose fallback random sampler uses a deterministic default seed.
    pub fn new() -> Self {
        Self {
            independent_sampler: RandomSampler::new(),
            engine: None,
        }
    }

    /// Creates a sampler whose fallback random sampler is seeded from a user-specified seed.
    ///
    /// The Sobol' sequence itself is deterministic and does not depend on the seed. The seed
    /// only affects parameters that fall back to independent sampling.
    pub fn seed_from_u64(seed: u64) -> Self {
        Self {
            independent_sampler: RandomSampler::seed_from_u64(seed),
            engine: None,
        }
    }
}

impl Sampler for QmcSampler {
    fn sample_independent(
        &mut self,
        ctx: &Context,
        storage: Arc<RwLock<dyn Storage>>,
        name: &str,
        distribution: &Distribution,
    ) -> Result<f64> {
        self.independent_sampler
            .sample_independent(ctx, storage, name, distribution)
    }

    fn support_joint_sampling(&self) -> bool {
        true
    }

    fn sample_joint(
        &mut self,
        ctx: &Context,
        storage: Arc<RwLock<dyn Storage>>,
        search_space: &HashMap<String, Distribution>,
    ) -> Result<HashMap<String, f64>> {
        if search_space.is_empty() {
            return Ok(HashMap::new());
        }

        let transform = SearchSpaceTransform::new(&to_numerical_search_space(search_space))?;
        let dim = transform.parameter_names().len();
        let engine = match &self.engine {
            Some(engine) if engine.dim() == dim => engine,
            _ => self.engine.insert(SobolEngine::new(dim)?),
        };

        // The index lives in the storage rather than in the engine, so that workers sharing a
        // study keep walking one sequence instead of each replaying it from the start.
        let sample_id = next_sample_id(ctx, &storage, search_space)?;
        let mut params = transform.untransform(&engine.nth_point(sample_id)?)?;

        // A categorical parameter occupies one coordinate spanning [0, cardinality), so flooring
        // it turns the coordinate into a choice index.
        for (name, distribution) in search_space {
            let Distribution::Categorical { cardinality } = distribution else {
                continue;
            };
            if let Some(value) = params.get_mut(name) {
                *value = value
                    .floor()
                    .clamp(0.0, cardinality.saturating_sub(1) as f64);
            }
        }
        Ok(params)
    }

    fn after_trial(
        &mut self,
        ctx: &Context,
        storage: Arc<RwLock<dyn Storage>>,
        state_values: &TrialStateValues,
    ) -> Result<()> {
        self.independent_sampler
            .after_trial(ctx, storage, state_values)
    }
}

/// Replaces categorical distributions so that the whole search space can be transformed into the
/// unit hypercube.
///
/// [`SearchSpaceTransform`] rejects categorical distributions, and Optuna's default encoding for
/// them is one-hot, which would spend one Sobol' dimension per choice. Mapping a categorical
/// parameter to `Float(0, cardinality)` keeps it to a single dimension, and flooring the
/// resulting coordinate gives every choice an interval of equal width. Going through an integer
/// distribution instead would round to nearest and halve the width of the two outermost choices.
/// This matches what Optuna's `QMCSampler.sample_relative` does.
fn to_numerical_search_space(
    search_space: &HashMap<String, Distribution>,
) -> HashMap<String, Distribution> {
    search_space
        .iter()
        .map(|(name, distribution)| {
            let distribution = match distribution {
                Distribution::Categorical { cardinality } => Distribution::Float {
                    low: 0.0,
                    high: *cardinality as f64,
                    step: None,
                    log: false,
                },
                other => other.clone(),
            };
            (name.clone(), distribution)
        })
        .collect()
}

/// Reserves the next index of the Sobol' sequence for this trial.
///
/// Like Optuna, the counter lives in a study system attribute keyed by the search space, so that
/// workers sharing a storage advance through one sequence rather than each replaying it from the
/// start.
///
/// The storage lock is held across both the read and the write, so concurrent threads within one
/// process cannot land on the same index. Separate processes each hold their own lock, and the
/// [`Storage`] trait has no API that reads and writes an attribute in one transaction, so two
/// processes can still read the same value and reserve the same index. Making that case exact
/// would need an atomic read-modify-write on the storage side.
fn next_sample_id(
    ctx: &Context,
    storage: &Arc<RwLock<dyn Storage>>,
    search_space: &HashMap<String, Distribution>,
) -> Result<u64> {
    let key = AttrKey::System(sample_id_key(search_space).into());
    let mut guard = storage.write().map_err(|e| {
        Error::with_reason(
            ErrorKind::StorageError,
            format!("Failed to acquire a storage guard: {e}"),
        )
    })?;

    let sample_id = match guard.get_study_attr(ctx.study_id, key.clone()) {
        Ok(value) => {
            value.parse::<u64>().map_err(|e| {
                Error::with_reason(
                    ErrorKind::SamplerError,
                    format!("Failed to parse the stored Sobol' sequence index {value:?}: {e}"),
                )
            })? + 1
        }
        Err(e) if matches!(e.kind, ErrorKind::AttrNotFound) => 0,
        Err(e) => return Err(e),
    };
    guard.set_study_attrs(
        ctx.study_id,
        Attrs::from([(key, sample_id.to_string())]),
        false,
    )?;
    Ok(sample_id)
}

/// Builds the study attribute key that holds the sequence index for a search space.
///
/// The key has to change whenever the search space does, because the number of dimensions and
/// the meaning of each dimension change with it. Optuna hashes the same information with
/// SHA-256; Rustuna uses FNV-1a to avoid a dependency, and the two are not meant to share a
/// counter.
fn sample_id_key(search_space: &HashMap<String, Distribution>) -> String {
    let mut names: Vec<_> = search_space.keys().collect();
    names.sort();

    let mut canonical = String::new();
    for name in names {
        canonical.push_str(name);
        canonical.push('=');
        canonical.push_str(&distribution_key(&search_space[name]));
        canonical.push(';');
    }
    format!("qmc:sobol:{:016x}", fnv1a64(canonical.as_bytes()))
}

/// Serializes a distribution into a stable string.
///
/// Floating-point fields are written as their bit patterns so that the result round-trips
/// exactly and does not depend on formatting.
fn distribution_key(distribution: &Distribution) -> String {
    fn float(value: f64) -> String {
        format!("0x{:016x}", value.to_bits())
    }

    match distribution {
        Distribution::Float {
            low,
            high,
            step,
            log,
        } => format!(
            "float(low={},high={},step={},log={log})",
            float(*low),
            float(*high),
            step.map_or_else(|| "none".to_string(), float),
        ),
        Distribution::Int {
            low,
            high,
            step,
            log,
        } => format!("int(low={low},high={high},step={step},log={log})"),
        Distribution::Categorical { cardinality } => format!("categorical(n={cardinality})"),
    }
}

/// 64-bit FNV-1a hash.
///
/// Rustuna needs a hash that stays the same across processes and compiler versions, which rules
/// out `std::collections::hash_map::DefaultHasher`.
fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf2_9ce4_8422_2325;
    for &byte in bytes {
        hash ^= u64::from(byte);
        hash = u64::wrapping_mul(hash, 0x0000_0100_0000_01b3);
    }
    hash
}

#[cfg(test)]
mod tests {
    use super::*;

    use rustuna_core::storage::InMemoryStorage;
    use rustuna_core::study::{create_study, Direction};

    #[test]
    fn follows_the_sobol_sequence_after_the_first_trial() -> Result<()> {
        let study = create_study(
            "qmc",
            InMemoryStorage::new(),
            QmcSampler::new(),
            vec![Direction::Minimize],
        )?;
        study.optimize(
            |mut trial| {
                let x = trial.suggest_float("x", 0.0, 1.0)?;
                Ok(vec![x])
            },
            5,
        )?;

        // The first trial has no joint search space yet and falls back to random sampling. Every
        // later trial walks the sequence, starting from its origin.
        let trials = study.get_trials()?;
        let sampled: Vec<f64> = trials[1..]
            .iter()
            .map(|trial| trial.internal_params["x"])
            .collect();
        assert_eq!(sampled, vec![0.0, 0.5, 0.75, 0.25]);
        Ok(())
    }

    #[test]
    fn assigns_dimensions_in_sorted_parameter_order() -> Result<()> {
        let study = create_study(
            "qmc",
            InMemoryStorage::new(),
            QmcSampler::new(),
            vec![Direction::Minimize],
        )?;
        // "b" is suggested first but sorts second, so it must take the second Sobol' coordinate.
        study.optimize(
            |mut trial| {
                let b = trial.suggest_float("b", 0.0, 1.0)?;
                let a = trial.suggest_float("a", 0.0, 1.0)?;
                Ok(vec![a + b])
            },
            4,
        )?;

        let trials = study.get_trials()?;
        let sampled: Vec<(f64, f64)> = trials[1..]
            .iter()
            .map(|trial| (trial.internal_params["a"], trial.internal_params["b"]))
            .collect();
        assert_eq!(sampled, vec![(0.0, 0.0), (0.5, 0.5), (0.75, 0.25)]);
        Ok(())
    }

    #[test]
    fn maps_every_kind_of_distribution_into_its_own_range() -> Result<()> {
        let study = create_study(
            "qmc",
            InMemoryStorage::new(),
            QmcSampler::new(),
            vec![Direction::Minimize],
        )?;
        study.optimize(
            |mut trial| {
                let linear = trial.suggest_float("linear", -10.0, 10.0)?;
                let logarithmic = trial.suggest_float("logarithmic", 1e-3, 1e3)?;
                let stepped = trial.suggest_float("stepped", 0.0, 10.0)?;
                let integer = trial.suggest_int("integer", -5, 5)?;
                let choice = *trial.suggest_categorical("choice", &[10, 20, 30, 40])?;

                assert!((-10.0..=10.0).contains(&linear));
                assert!((1e-3..=1e3).contains(&logarithmic));
                assert!((0.0..=10.0).contains(&stepped));
                assert!((-5..=5).contains(&integer));
                assert!([10, 20, 30, 40].contains(&choice));
                Ok(vec![linear + integer as f64 + choice as f64])
            },
            32,
        )?;
        Ok(())
    }

    #[test]
    fn spreads_categorical_choices_evenly() -> Result<()> {
        let study = create_study(
            "qmc",
            InMemoryStorage::new(),
            QmcSampler::new(),
            vec![Direction::Minimize],
        )?;
        study.optimize(
            |mut trial| {
                let choice = *trial.suggest_categorical("choice", &[0, 1, 2, 3])?;
                Ok(vec![choice as f64])
            },
            17,
        )?;

        // A categorical parameter takes one coordinate spanning [0, 4). Because the Sobol'
        // sequence stratifies that coordinate, 16 sequence points must land four times on each
        // of the four choices.
        let trials = study.get_trials()?;
        let mut counts = [0; 4];
        for trial in &trials[1..] {
            let index = trial.internal_params["choice"];
            assert_eq!(index, index.floor(), "choice must be a whole index");
            counts[index as usize] += 1;
        }
        assert_eq!(counts, [4, 4, 4, 4]);
        Ok(())
    }

    #[test]
    fn keys_the_counter_by_search_space() {
        let x = Distribution::new_float(0.0, 1.0, None, false);
        let y = Distribution::new_float(0.0, 2.0, None, false);

        let one = HashMap::from([("x".to_string(), x.clone())]);
        let same = HashMap::from([("x".to_string(), x.clone())]);
        assert_eq!(sample_id_key(&one), sample_id_key(&same));

        // A different bound, a different name, and an extra parameter each have to move the
        // counter, because they change what the sequence coordinates mean.
        assert_ne!(
            sample_id_key(&one),
            sample_id_key(&HashMap::from([("x".to_string(), y.clone())]))
        );
        assert_ne!(
            sample_id_key(&one),
            sample_id_key(&HashMap::from([("y".to_string(), x.clone())]))
        );
        assert_ne!(
            sample_id_key(&one),
            sample_id_key(&HashMap::from([
                ("x".to_string(), x.clone()),
                ("y".to_string(), y),
            ]))
        );
    }

    #[test]
    fn separates_counters_of_different_search_spaces() -> Result<()> {
        let study = create_study(
            "qmc",
            InMemoryStorage::new(),
            QmcSampler::new(),
            vec![Direction::Minimize],
        )?;
        // "y" only exists while the first trials run, so the joint search space shrinks from
        // {x, y} to {x} and the sampler starts a fresh counter for the smaller space.
        study.optimize(
            |mut trial| {
                let x = trial.suggest_float("x", 0.0, 1.0)?;
                let y = if trial.number < 3 {
                    trial.suggest_float("y", 0.0, 1.0)?
                } else {
                    0.0
                };
                Ok(vec![x + y])
            },
            6,
        )?;

        let trials = study.get_trials()?;
        // Trials 1 and 2 walk the two-dimensional sequence, then trials 4 and 5 restart in one
        // dimension once "y" has dropped out of the joint search space.
        assert_eq!(trials[1].internal_params["x"], 0.0);
        assert_eq!(trials[2].internal_params["x"], 0.5);
        assert_eq!(trials[4].internal_params["x"], 0.0);
        assert_eq!(trials[5].internal_params["x"], 0.5);
        Ok(())
    }
}
