[package]
name = "rustuna_c"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
rustuna_core = { workspace = true }
rustuna_samplers = { workspace = true }

[build-dependencies]
cbindgen = "0.26.0"