name: Tests and checks (JavaScript)
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/checks_js.yml'
      - 'rustuna_js/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rustuna_core/src/**'

permissions:
  contents: read
jobs:
  js_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Installing biome.js
        working-directory: rustuna_js
        run: npm i -g biome
      - name: Lint
        working-directory: rustuna_js
        run: biome ci examples/*.ts test/*.mjs
      - name: Cache cargo binaries
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-
      - name: Install wasm-bindgen-cli and wasm-opt
        run: |
          WASM_BINDGEN_VERSION=$(cargo metadata --format-version 1 --locked | jq -r '.packages[] | select(.name == "wasm-bindgen") | .version')
          if ! command -v wasm-bindgen &> /dev/null; then
            cargo install wasm-bindgen-cli --version $WASM_BINDGEN_VERSION
          fi
          if ! command -v wasm-opt &> /dev/null; then
            cargo install wasm-opt
          fi
      - name: Build JS binding
        working-directory: rustuna_js
        run: ./build.sh
      - name: Run tsc
        working-directory: rustuna_js
        run: tsc --noEmit --project tsconfig.examples.json
      - name: Run tests
        working-directory: rustuna_js
        run: node --test
